// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type AccountValueOverTimeResponse = {
    history: Array<AccountValueSnapshotDaily>;
    current_value: string;
};

/**
 * Serializer for AccountValueSnapshot model.
 */
export type AccountValueSnapshotDaily = {
    /**
     * Date of the value measurement
     */
    readonly date: string;
    /**
     * Account value on this date
     */
    value: number;
};

export type AllTickers = {
    tickers: Array<string>;
};

export type AssetAllocation = {
    total_value: number;
    total_gain_this_year: number;
    allocations: Array<AssetAllocationItem>;
};

export type AssetAllocationItem = {
    instrument_name: string;
    instrument_ticker: string;
    instrument_logo: string | null;
    instrument_icon: string | null;
    value: number;
    percentage: number;
};

/**
 * Serializer for authentication test response
 */
export type AuthTestResponse = {
    /**
     * Authentication success message
     */
    message: string;
    /**
     * Role of the authenticated user
     */
    user_role: string;
    /**
     * ID of the authenticated user
     */
    user_id: number;
};

export type Chat = {
    readonly id: string;
    title: string;
    readonly created_at: string;
    readonly updated_at: string;
    readonly message_count: number;
};

export type ChatDetail = {
    readonly id: string;
    title: string;
    readonly created_at: string;
    readonly updated_at: string;
    readonly messages: Array<ChatMessage>;
};

export type ChatDetailRequest = {
    title: string;
};

export type ChatMessage = {
    readonly id: string;
    role: RoleEnum;
    readonly content: string;
    readonly createdAt: string | null;
};

export type ClerkLoginRequest = {
    email: string;
    password: string;
};

export type CreateChatMessageRequest = {
    content: string;
    role?: RoleEnum;
};

export type CreateChatRequest = {
    first_message: string;
};

export type CreateLimitOrderRequest = {
    ticker: string;
    volume: string;
    is_buy: boolean;
    limit_price: string;
};

export type CreateMarketOrderRequest = {
    ticker: string;
    volume: string;
    is_buy: boolean;
};

export type CurrentAccountValue = {
    total_account_value: number;
    gain: number;
    gain_percentage: number | null;
};

export type DepositHistory = {
    readonly id: string;
    /**
     * Deposit Amount
     */
    readonly amount: string;
    readonly deposited_at: string;
};

export type DepositMoney = {
    amount: string;
};

export type DepositMoneyRequest = {
    amount: string;
};

/**
 * * `push` - push
 * * `mail` - mail
 */
export type FormatEnum = 'push' | 'mail';

export type Graph = {
    readonly id: string;
    name: string;
    raw_graph_data: unknown;
    active?: boolean;
    repeat?: boolean;
};

export type GraphEffect = {
    readonly created_at: string;
    effect: GraphEffectDetail;
    success: boolean;
};

export type GraphEffectDetail = ({
    effect_type: 'transaction';
} & GraphTransactionEffect) | ({
    effect_type: 'notification';
} & GraphNotificationEffect);

export type GraphNotificationEffect = {
    message: string;
    format: FormatEnum;
    readonly effect_type: string;
};

export type GraphRequest = {
    name: string;
    raw_graph_data: unknown;
    active?: boolean;
    repeat?: boolean;
};

export type GraphResult = {
    action: unknown;
};

export type GraphTransactionEffect = {
    instrument: InstrumentName;
    is_buy: boolean;
    amount: number;
    action_price: number;
    readonly effect_type: string;
};

export type GraphUpdateRequest = {
    name?: string;
    raw_graph_data?: unknown;
    active?: boolean;
    repeat?: boolean;
};

export type HistoryEntry = {
    /**
     * Date of the transaction
     */
    timestamp: string;
    /**
     * True if the transaction was a buy False if it was a sell
     */
    is_buy: boolean;
    /**
     * Number of shares traded
     */
    quantity: string;
    /**
     * Price per share at the time of transaction
     */
    share_price: number;
    /**
     * Acquisition price (null for SELL transactions)
     */
    acquisition_price: number | null;
};

export type Insight = {
    sentiment?: string | null;
    sentiment_reasoning?: string | null;
    ticker?: string | null;
};

export type InstrumentList = {
    readonly id: string;
    /**
     * Ticker Symbol
     */
    ticker: string;
    /**
     * Security type, e.g. 'CS' (Common Stock), 'ETF', 'Crypto'.
     */
    type?: string | null;
    /**
     * Indicates whether the ticker is actively traded.
     */
    active?: boolean;
    name: string;
    market: MarketEnum;
    market_cap?: string | null;
    currency_name?: string;
    icon?: string | null;
    logo?: string | null;
};

export type InstrumentName = {
    /**
     * Ticker Symbol
     */
    ticker: string;
};

export type InstrumentRetrieve = {
    readonly id: string;
    /**
     * Ticker Symbol
     */
    ticker: string;
    /**
     * Security type, e.g. 'CS' (Common Stock), 'ETF', 'Crypto'.
     */
    type?: string | null;
    /**
     * Indicates whether the ticker is actively traded.
     */
    active?: boolean;
    name: string;
    /**
     * Central Index Key assigned by the SEC.
     */
    cik?: string | null;
    market: MarketEnum;
    market_cap?: string | null;
    /**
     * Composite Financial Instrument Global Identifier.
     */
    composite_figi?: string | null;
    currency_name?: string;
    /**
     * Locale where the ticker is traded, e.g. 'US'.
     *
     * * `us` - United States
     * * `global` - Global
     */
    locale: LocaleEnum;
    /**
     * Code of the primary exchange where the ticker is traded.
     */
    primary_exchange?: string | null;
    share_class_figi?: string | null;
    description?: string | null;
    /**
     * Base symbol for related tickers.
     */
    ticker_root?: string | null;
    /**
     * Suffix for ticker if applicable.
     */
    ticker_suffix?: string | null;
    homepage_url?: string | null;
    /**
     * Date when the ticker was first listed.
     */
    list_date?: string | null;
    phone_number?: string | null;
    /**
     * Shares Outstanding (Share Class)
     * Number of shares outstanding for this share class.
     */
    share_class_shares_outstanding?: number | null;
    /**
     * Standard Industrial Classification code.
     */
    sic_code?: string | null;
    sic_description?: string | null;
    total_employees?: number | null;
    weighted_shares_outstanding?: number | null;
    readonly address: {
        address1: string | null;
        address2: string | null;
        city: string | null;
        state: string | null;
        postal_code: string | null;
    };
    icon?: string | null;
    logo?: string | null;
};

export type InstrumentWithPrice = {
    readonly id: string;
    /**
     * Ticker Symbol
     */
    ticker: string;
    /**
     * Security type, e.g. 'CS' (Common Stock), 'ETF', 'Crypto'.
     */
    type?: string | null;
    /**
     * Indicates whether the ticker is actively traded.
     */
    active?: boolean;
    name: string;
    market: MarketEnum;
    market_cap?: string | null;
    currency_name?: string;
    icon?: string | null;
    logo?: string | null;
    price_info: PriceDailySummary;
    readonly is_watched: boolean;
};

export type Investor = {
    readonly id: string;
    readonly clerk_id: string;
    readonly balance: string;
    blocked_funds?: string;
    /**
     * User's preferred language (e.g., 'en', 'pl')
     */
    language?: string;
    watching_instruments?: Array<string>;
};

/**
 * Serializer for investor statistics data.
 */
export type InvestorStats = {
    /**
     * Today's gain in currency
     */
    todays_gain: number;
    /**
     * Total gain in currency
     */
    total_gain: number;
    /**
     * Total amount invested
     */
    invested: number;
    /**
     * Total account value
     */
    total_value: number;
};

export type LimitOrder = {
    readonly id: string;
    readonly ticker: string;
    detail_type: number;
    detail: LimitOrderDetails;
};

export type LimitOrderDetails = {
    readonly detail_type: string;
    volume: string;
    volume_processed?: string;
    is_buy: boolean;
    limit_price: string;
};

/**
 * * `us` - United States
 * * `global` - Global
 */
export type LocaleEnum = 'us' | 'global';

export type MarketCurrencies = {
    crypto?: string | null;
    fx?: string | null;
};

/**
 * * `stocks` - Stocks
 * * `crypto` - Crypto
 * * `fx` - Foreign Exchange
 * * `otc` - Over-the-Counter
 * * `indices` - Indices
 */
export type MarketEnum = 'stocks' | 'crypto' | 'fx' | 'otc' | 'indices';

export type MarketExchanges = {
    nasdaq?: string | null;
    nyse?: string | null;
    otc?: string | null;
};

export type MarketHoliday = {
    close?: string | null;
    date?: string | null;
    exchange?: string | null;
    name?: string | null;
    open?: string | null;
    status?: string | null;
};

export type MarketIndices = {
    s_and_p?: string | null;
    societe_generale?: string | null;
    cgi?: string | null;
    msci?: string | null;
    ftse_russell?: string | null;
    mstar?: string | null;
    mstarc?: string | null;
    cccy?: string | null;
    nasdaq?: string | null;
    dow_jones?: string | null;
};

export type MarketOrder = {
    readonly id: string;
    readonly ticker: string;
    detail_type: number;
    detail: MarketOrderDetails;
};

export type MarketOrderDetails = {
    readonly detail_type: string;
    volume: string;
    volume_processed?: string;
    is_buy: boolean;
};

export type MarketStatus = {
    after_hours?: boolean | null;
    currencies?: MarketCurrencies | null;
    early_hours?: boolean | null;
    exchanges?: MarketExchanges | null;
    indicesGroups?: MarketIndices | null;
    market?: string | null;
    server_time?: string | null;
};

export type MostTradedItem = {
    symbol: string;
    no_trades: number;
    buys: number;
    sells: number;
    avg_gain: number;
    avg_loss: number;
};

export type NotificationConfig = {
    readonly id: string;
    /**
     * Send Email
     */
    is_email?: boolean;
    /**
     * Send Push
     */
    is_push?: boolean;
    /**
     * Send WebSocket
     */
    is_websocket?: boolean;
    is_active?: boolean;
    readonly created_at: string;
};

export type NotificationConfigCreate = {
    is_email: boolean;
    is_push: boolean;
    is_websocket: boolean;
};

export type NotificationConfigCreateRequest = {
    is_email: boolean;
    is_push: boolean;
    is_websocket: boolean;
};

export type NotificationConfigRequest = {
    /**
     * Send Email
     */
    is_email?: boolean;
    /**
     * Send Push
     */
    is_push?: boolean;
    /**
     * Send WebSocket
     */
    is_websocket?: boolean;
    is_active?: boolean;
};

/**
 * Serializer for NotificationHistory model.
 */
export type NotificationHistory = {
    readonly id: string;
    /**
     * Type of the notification
     */
    type: string;
    /**
     * Notification message in English
     */
    message_en: string;
    /**
     * Notification message in Polish
     */
    message_pl: string;
    /**
     * When the notification was sent
     */
    sent_at: string;
    readonly created_at: string;
    readonly updated_at: string;
};

export type Order = {
    readonly id: string;
    readonly ticker: string;
    detail_type: number;
    detail: OrderDetail;
};

export type OrderCreationError = {
    reason: ReasonEnum;
    detail: string;
};

export type OrderDetail = ({
    detail_type: 'market';
} & MarketOrderDetails) | ({
    detail_type: 'limit';
} & LimitOrderDetails);

export type OwnedShare = {
    name: string;
    symbol: string;
    volume: number;
    value: number;
    gain: number;
    gain_percentage: number | null;
};

export type PaginatedDepositHistoryList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<DepositHistory>;
};

export type PaginatedGraphEffectList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<GraphEffect>;
};

export type PaginatedGraphList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<Graph>;
};

export type PaginatedInstrumentListList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<InstrumentList>;
};

export type PaginatedInstrumentWithPriceList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<InstrumentWithPrice>;
};

export type PaginatedPriceAlertList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<PriceAlert>;
};

export type PatchedChatDetailRequest = {
    title?: string;
};

export type PatchedGraphUpdateRequest = {
    name?: string;
    raw_graph_data?: unknown;
    active?: boolean;
    repeat?: boolean;
};

export type PatchedInvestorRequest = {
    blocked_funds?: string;
    /**
     * User's preferred language (e.g., 'en', 'pl')
     */
    language?: string;
    watching_instruments?: Array<string>;
};

export type PatchedPriceAlertRequest = {
    threshold_type?: ThresholdTypeEnum;
    threshold_value?: string;
    notification_config?: NotificationConfigRequest;
};

export type PatchedWatchedTickersTickerRequest = {
    /**
     * Whether the instrument is now being watched
     */
    is_watched?: boolean;
};

export type Position = {
    /**
     * Ticker symbol
     */
    symbol: string;
    /**
     * Instrument name
     */
    name: string;
    icon: string | null;
    /**
     * Total quantity of shares
     */
    quantity: string;
    /**
     * Current market value
     */
    market_value: number;
    /**
     * Total gain or loss
     */
    gain: number;
    /**
     * Total gain or loss percentage
     */
    gain_percentage: number | null;
    /**
     * Transaction history
     */
    history: Array<HistoryEntry>;
};

export type PriceAlert = {
    readonly id: string;
    readonly instrument_name: string;
    readonly instrument_ticker: string;
    threshold_type: ThresholdTypeEnum;
    threshold_value: string;
    notification_config: NotificationConfig;
};

export type PriceAlertCreate = {
    readonly id: string;
    threshold_type: ThresholdTypeEnum;
    threshold_value: string;
    notification_config: NotificationConfigCreate;
};

export type PriceAlertCreateRequest = {
    threshold_type: ThresholdTypeEnum;
    threshold_value: string;
    notification_config: NotificationConfigCreateRequest;
};

export type PriceAlertRequest = {
    threshold_type: ThresholdTypeEnum;
    threshold_value: string;
    notification_config: NotificationConfigRequest;
};

export type PriceBar = {
    timestamp: string;
    open: string;
    high: string;
    low: string;
    close: string;
    volume: string;
    transactions?: number | null;
    volume_weighted_average_price?: string | null;
};

export type PriceDaily = {
    open: string;
    high: string;
    low: string;
    close: string;
    volume: string;
    volume_weighted_average_price: string;
};

export type PriceDailySummary = {
    readonly current_price: string;
    ticker: string;
    daily_summary: PriceDaily;
    todays_change: string;
    todays_change_percent: string;
    last_updated: string;
};

export type PriceTimestampRequest = {
    price: string;
    timestamp: string;
};

export type Publisher = {
    favicon_url?: string | null;
    homepage_url?: string | null;
    logo_url?: string | null;
    name?: string | null;
};

export type PushNotificationRequest = {
    endpoint: string;
    p256dh: string;
    auth: string;
};

/**
 * * `funds` - funds
 * * `assets` - assets
 * * `unknown` - unknown
 */
export type ReasonEnum = 'funds' | 'assets' | 'unknown';

/**
 * * `user` - user
 * * `assistant` - assistant
 */
export type RoleEnum = 'user' | 'assistant';

export type RunGraphRequest = {
    time_at?: string;
    prices?: Array<TickerPricesRequest>;
};

export type RunGraphResult = {
    results: Array<GraphResult>;
};

/**
 * Serializer for simple OK response
 */
export type SimpleResponse = {
    /**
     * Simple confirmation response
     */
    OK?: string;
};

/**
 * Serializer for status endpoint response
 */
export type StatusResponse = {
    /**
     * Status message indicating the application is running
     */
    message: string;
};

/**
 * * `above` - Above
 * * `below` - Below
 */
export type ThresholdTypeEnum = 'above' | 'below';

export type TickerNews = {
    amp_url?: string | null;
    article_url?: string | null;
    author?: string | null;
    description?: string | null;
    id?: string | null;
    image_url?: string | null;
    insights?: Array<Insight> | null;
    keywords?: Array<string> | null;
    published_utc?: string | null;
    publisher?: Publisher | null;
    tickers?: Array<string> | null;
    title?: string | null;
};

export type TickerPricesRequest = {
    ticker: string;
    prices: Array<PriceTimestampRequest>;
};

export type TradingOverview = {
    total_trades: number;
    buys: number;
    sells: number;
    total_gain: number;
};

export type VapidPublicKey = {
    public_key: string;
};

/**
 * Serializer for watched tickers with icon and ticker information.
 */
export type WatchedTicker = {
    /**
     * Ticker Symbol
     */
    ticker: string;
    name: string;
    icon?: string | null;
    logo?: string | null;
};

export type WatchedTickersTicker = {
    /**
     * Whether the instrument is now being watched
     */
    is_watched: boolean;
};

/**
 * Serializer for AccountValueSnapshot model.
 */
export type AccountValueSnapshotDailyWritable = {
    /**
     * Account value on this date
     */
    value: number;
};

export type ChatWritable = {
    title: string;
};

export type ChatDetailWritable = {
    title: string;
};

export type GraphWritable = {
    name: string;
    raw_graph_data: unknown;
    active?: boolean;
    repeat?: boolean;
};

export type GraphEffectWritable = {
    success: boolean;
};

export type GraphNotificationEffectWritable = {
    message: string;
    format: FormatEnum;
};

export type GraphTransactionEffectWritable = {
    instrument: InstrumentName;
    is_buy: boolean;
    amount: number;
    action_price: number;
};

export type InstrumentListWritable = {
    /**
     * Ticker Symbol
     */
    ticker: string;
    /**
     * Security type, e.g. 'CS' (Common Stock), 'ETF', 'Crypto'.
     */
    type?: string | null;
    /**
     * Indicates whether the ticker is actively traded.
     */
    active?: boolean;
    name: string;
    market: MarketEnum;
    market_cap?: string | null;
    currency_name?: string;
    icon?: string | null;
    logo?: string | null;
};

export type InstrumentRetrieveWritable = {
    /**
     * Ticker Symbol
     */
    ticker: string;
    /**
     * Security type, e.g. 'CS' (Common Stock), 'ETF', 'Crypto'.
     */
    type?: string | null;
    /**
     * Indicates whether the ticker is actively traded.
     */
    active?: boolean;
    name: string;
    /**
     * Central Index Key assigned by the SEC.
     */
    cik?: string | null;
    market: MarketEnum;
    market_cap?: string | null;
    /**
     * Composite Financial Instrument Global Identifier.
     */
    composite_figi?: string | null;
    currency_name?: string;
    /**
     * Locale where the ticker is traded, e.g. 'US'.
     *
     * * `us` - United States
     * * `global` - Global
     */
    locale: LocaleEnum;
    /**
     * Code of the primary exchange where the ticker is traded.
     */
    primary_exchange?: string | null;
    share_class_figi?: string | null;
    description?: string | null;
    /**
     * Base symbol for related tickers.
     */
    ticker_root?: string | null;
    /**
     * Suffix for ticker if applicable.
     */
    ticker_suffix?: string | null;
    homepage_url?: string | null;
    /**
     * Date when the ticker was first listed.
     */
    list_date?: string | null;
    phone_number?: string | null;
    /**
     * Shares Outstanding (Share Class)
     * Number of shares outstanding for this share class.
     */
    share_class_shares_outstanding?: number | null;
    /**
     * Standard Industrial Classification code.
     */
    sic_code?: string | null;
    sic_description?: string | null;
    total_employees?: number | null;
    weighted_shares_outstanding?: number | null;
    icon?: string | null;
    logo?: string | null;
};

export type InstrumentWithPriceWritable = {
    /**
     * Ticker Symbol
     */
    ticker: string;
    /**
     * Security type, e.g. 'CS' (Common Stock), 'ETF', 'Crypto'.
     */
    type?: string | null;
    /**
     * Indicates whether the ticker is actively traded.
     */
    active?: boolean;
    name: string;
    market: MarketEnum;
    market_cap?: string | null;
    currency_name?: string;
    icon?: string | null;
    logo?: string | null;
};

export type InvestorWritable = {
    blocked_funds?: string;
    /**
     * User's preferred language (e.g., 'en', 'pl')
     */
    language?: string;
    watching_instruments?: Array<string>;
};

export type LimitOrderWritable = {
    detail_type: number;
    detail: LimitOrderDetailsWritable;
};

export type LimitOrderDetailsWritable = {
    volume: string;
    volume_processed?: string;
    is_buy: boolean;
    limit_price: string;
};

export type MarketOrderWritable = {
    detail_type: number;
    detail: MarketOrderDetailsWritable;
};

export type MarketOrderDetailsWritable = {
    volume: string;
    volume_processed?: string;
    is_buy: boolean;
};

export type NotificationConfigWritable = {
    /**
     * Send Email
     */
    is_email?: boolean;
    /**
     * Send Push
     */
    is_push?: boolean;
    /**
     * Send WebSocket
     */
    is_websocket?: boolean;
    is_active?: boolean;
};

export type NotificationConfigCreateRequestWritable = {
    is_email: boolean;
    is_push: boolean;
    is_websocket: boolean;
    push_subscription?: PushNotificationRequest;
};

/**
 * Serializer for NotificationHistory model.
 */
export type NotificationHistoryWritable = {
    /**
     * Type of the notification
     */
    type: string;
    /**
     * Notification message in English
     */
    message_en: string;
    /**
     * Notification message in Polish
     */
    message_pl: string;
    /**
     * When the notification was sent
     */
    sent_at: string;
};

export type OrderWritable = {
    detail_type: number;
};

export type PaginatedDepositHistoryListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<unknown>;
};

export type PriceAlertWritable = {
    threshold_type: ThresholdTypeEnum;
    threshold_value: string;
    notification_config: NotificationConfigWritable;
};

export type PriceAlertCreateWritable = {
    threshold_type: ThresholdTypeEnum;
    threshold_value: string;
    notification_config: NotificationConfigCreate;
};

export type PriceAlertCreateRequestWritable = {
    instrument_ticker: string;
    threshold_type: ThresholdTypeEnum;
    threshold_value: string;
    notification_config: NotificationConfigCreateRequestWritable;
};

export type PriceDailySummaryWritable = {
    ticker: string;
    daily_summary: PriceDaily;
    todays_change: string;
    todays_change_percent: string;
    last_updated: string;
};

export type AuthSignInCreateData = {
    body: ClerkLoginRequest;
    path?: never;
    query?: never;
    url: '/api/auth/sign-in/';
};

export type AuthSignInCreateErrors = {
    /**
     * Invalid credentials or user not found.
     */
    400: unknown;
    /**
     * Password verification failed.
     */
    401: unknown;
    /**
     * Clerk SDK error or other internal server error.
     */
    500: unknown;
};

export type AuthSignInCreateResponses = {
    /**
     * Sign-in successful, token returned.
     */
    200: unknown;
};

export type ChatsListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/chats/';
};

export type ChatsListResponses = {
    200: Array<Chat>;
};

export type ChatsListResponse = ChatsListResponses[keyof ChatsListResponses];

export type ChatsCreateData = {
    body: CreateChatRequest;
    path?: never;
    query?: never;
    url: '/api/chats/';
};

export type ChatsCreateResponses = {
    201: Chat;
};

export type ChatsCreateResponse = ChatsCreateResponses[keyof ChatsCreateResponses];

export type ChatsDestroyData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/chats/{id}/';
};

export type ChatsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type ChatsDestroyResponse = ChatsDestroyResponses[keyof ChatsDestroyResponses];

export type ChatsRetrieveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/chats/{id}/';
};

export type ChatsRetrieveResponses = {
    200: ChatDetail;
};

export type ChatsRetrieveResponse = ChatsRetrieveResponses[keyof ChatsRetrieveResponses];

export type ChatsPartialUpdateData = {
    body?: PatchedChatDetailRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/chats/{id}/';
};

export type ChatsPartialUpdateResponses = {
    200: ChatDetail;
};

export type ChatsPartialUpdateResponse = ChatsPartialUpdateResponses[keyof ChatsPartialUpdateResponses];

export type ChatsUpdateData = {
    body: ChatDetailRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/chats/{id}/';
};

export type ChatsUpdateResponses = {
    200: ChatDetail;
};

export type ChatsUpdateResponse = ChatsUpdateResponses[keyof ChatsUpdateResponses];

export type ChatsMessagesCreateData = {
    body: CreateChatMessageRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/chats/{id}/messages/';
};

export type ChatsMessagesCreateResponses = {
    201: {
        status?: string;
    };
};

export type ChatsMessagesCreateResponse = ChatsMessagesCreateResponses[keyof ChatsMessagesCreateResponses];

export type GraphLangListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
    };
    url: '/api/graph_lang/';
};

export type GraphLangListResponses = {
    200: PaginatedGraphList;
};

export type GraphLangListResponse = GraphLangListResponses[keyof GraphLangListResponses];

export type GraphLangCreateData = {
    body: GraphRequest;
    path?: never;
    query?: never;
    url: '/api/graph_lang/';
};

export type GraphLangCreateResponses = {
    201: Graph;
};

export type GraphLangCreateResponse = GraphLangCreateResponses[keyof GraphLangCreateResponses];

export type GraphLangDestroyData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/graph_lang/{id}/';
};

export type GraphLangDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type GraphLangDestroyResponse = GraphLangDestroyResponses[keyof GraphLangDestroyResponses];

export type GraphLangRetrieveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/graph_lang/{id}/';
};

export type GraphLangRetrieveResponses = {
    200: Graph;
};

export type GraphLangRetrieveResponse = GraphLangRetrieveResponses[keyof GraphLangRetrieveResponses];

export type GraphLangPartialUpdateData = {
    body?: PatchedGraphUpdateRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/graph_lang/{id}/';
};

export type GraphLangPartialUpdateResponses = {
    200: Graph;
};

export type GraphLangPartialUpdateResponse = GraphLangPartialUpdateResponses[keyof GraphLangPartialUpdateResponses];

export type GraphLangUpdateData = {
    body?: GraphUpdateRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/graph_lang/{id}/';
};

export type GraphLangUpdateResponses = {
    200: Graph;
};

export type GraphLangUpdateResponse = GraphLangUpdateResponses[keyof GraphLangUpdateResponses];

export type GraphLangResultsListData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
    };
    url: '/api/graph_lang/{id}/results/';
};

export type GraphLangResultsListResponses = {
    200: PaginatedGraphEffectList;
};

export type GraphLangResultsListResponse = GraphLangResultsListResponses[keyof GraphLangResultsListResponses];

export type GraphLangRunCreateData = {
    body?: RunGraphRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/graph_lang/{id}/run/';
};

export type GraphLangRunCreateResponses = {
    200: RunGraphResult;
};

export type GraphLangRunCreateResponse = GraphLangRunCreateResponses[keyof GraphLangRunCreateResponses];

export type InstrumentsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
        /**
         * A search term.
         */
        search?: string;
        watched?: boolean;
    };
    url: '/api/instruments/';
};

export type InstrumentsListResponses = {
    200: PaginatedInstrumentListList;
};

export type InstrumentsListResponse = InstrumentsListResponses[keyof InstrumentsListResponses];

export type InstrumentsDetailRetrieveData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by cik.
         */
        cik?: string;
        /**
         * Filter by composite_figi.
         */
        composite_figi?: string;
        /**
         * Filter by id.
         */
        id?: string;
        /**
         * Filter by share_class_figi.
         */
        share_class_figi?: string;
        /**
         * Filter by ticker.
         */
        ticker?: string;
    };
    url: '/api/instruments/detail/';
};

export type InstrumentsDetailRetrieveResponses = {
    200: InstrumentRetrieve;
};

export type InstrumentsDetailRetrieveResponse = InstrumentsDetailRetrieveResponses[keyof InstrumentsDetailRetrieveResponses];

export type InstrumentsTickersRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/instruments/tickers/';
};

export type InstrumentsTickersRetrieveResponses = {
    200: AllTickers;
};

export type InstrumentsTickersRetrieveResponse = InstrumentsTickersRetrieveResponses[keyof InstrumentsTickersRetrieveResponses];

export type InstrumentsWithPricesListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
        /**
         * A search term.
         */
        search?: string;
        watched?: boolean;
    };
    url: '/api/instruments/with-prices/';
};

export type InstrumentsWithPricesListResponses = {
    200: PaginatedInstrumentWithPriceList;
};

export type InstrumentsWithPricesListResponse = InstrumentsWithPricesListResponses[keyof InstrumentsWithPricesListResponses];

export type InvestorsRetrieveData = {
    body?: never;
    path: {
        clerk_id: string;
    };
    query?: never;
    url: '/api/investors/{clerk_id}/';
};

export type InvestorsRetrieveResponses = {
    200: Investor;
};

export type InvestorsRetrieveResponse = InvestorsRetrieveResponses[keyof InvestorsRetrieveResponses];

export type InvestorsPartialUpdateData = {
    body?: PatchedInvestorRequest;
    path: {
        clerk_id: string;
    };
    query?: never;
    url: '/api/investors/{clerk_id}/';
};

export type InvestorsPartialUpdateResponses = {
    200: Investor;
};

export type InvestorsPartialUpdateResponse = InvestorsPartialUpdateResponses[keyof InvestorsPartialUpdateResponses];

export type InvestorsDepositCreateData = {
    body: DepositMoneyRequest;
    path?: never;
    query?: never;
    url: '/api/investors/deposit/';
};

export type InvestorsDepositCreateResponses = {
    200: DepositMoney;
};

export type InvestorsDepositCreateResponse = InvestorsDepositCreateResponses[keyof InvestorsDepositCreateResponses];

export type InvestorsDepositHistoryListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
    };
    url: '/api/investors/deposit-history/';
};

export type InvestorsDepositHistoryListResponses = {
    200: PaginatedDepositHistoryList;
};

export type InvestorsDepositHistoryListResponse = InvestorsDepositHistoryListResponses[keyof InvestorsDepositHistoryListResponses];

export type InvestorsMeRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/investors/me/';
};

export type InvestorsMeRetrieveResponses = {
    200: Investor;
};

export type InvestorsMeRetrieveResponse = InvestorsMeRetrieveResponses[keyof InvestorsMeRetrieveResponses];

export type InvestorsMePartialUpdateData = {
    body?: PatchedInvestorRequest;
    path?: never;
    query?: never;
    url: '/api/investors/me/';
};

export type InvestorsMePartialUpdateResponses = {
    200: Investor;
};

export type InvestorsMePartialUpdateResponse = InvestorsMePartialUpdateResponses[keyof InvestorsMePartialUpdateResponses];

export type InvestorsMeAccountValueRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/investors/me/account-value/';
};

export type InvestorsMeAccountValueRetrieveResponses = {
    200: AccountValueOverTimeResponse;
};

export type InvestorsMeAccountValueRetrieveResponse = InvestorsMeAccountValueRetrieveResponses[keyof InvestorsMeAccountValueRetrieveResponses];

export type InvestorsMeNotificationsListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/investors/me/notifications/';
};

export type InvestorsMeNotificationsListResponses = {
    200: Array<NotificationHistory>;
};

export type InvestorsMeNotificationsListResponse = InvestorsMeNotificationsListResponses[keyof InvestorsMeNotificationsListResponses];

export type InvestorsMeWatchedTickersListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/investors/me/watched-tickers/';
};

export type InvestorsMeWatchedTickersListResponses = {
    200: Array<WatchedTicker>;
};

export type InvestorsMeWatchedTickersListResponse = InvestorsMeWatchedTickersListResponses[keyof InvestorsMeWatchedTickersListResponses];

export type InvestorsMeWatchedTickersPartialUpdateData = {
    body?: PatchedWatchedTickersTickerRequest;
    path: {
        instrument_id: string;
    };
    query?: never;
    url: '/api/investors/me/watched-tickers/{instrument_id}/';
};

export type InvestorsMeWatchedTickersPartialUpdateResponses = {
    200: WatchedTickersTicker;
};

export type InvestorsMeWatchedTickersPartialUpdateResponse = InvestorsMeWatchedTickersPartialUpdateResponses[keyof InvestorsMeWatchedTickersPartialUpdateResponses];

export type MarketsHolidaysListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/markets/holidays/';
};

export type MarketsHolidaysListResponses = {
    200: Array<MarketHoliday>;
};

export type MarketsHolidaysListResponse = MarketsHolidaysListResponses[keyof MarketsHolidaysListResponses];

export type MarketsStatusRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/markets/status/';
};

export type MarketsStatusRetrieveResponses = {
    200: MarketStatus;
};

export type MarketsStatusRetrieveResponse = MarketsStatusRetrieveResponses[keyof MarketsStatusRetrieveResponses];

export type NewsListData = {
    body?: never;
    path?: never;
    query?: {
        number_of_news?: number;
        /**
         * * `asc` - asc
         * * `desc` - desc
         */
        order?: 'asc' | 'desc';
        published_utc?: string;
        published_utc_gte?: string;
        published_utc_lte?: string;
        sort?: string;
        ticker?: string;
    };
    url: '/api/news/';
};

export type NewsListResponses = {
    200: Array<TickerNews>;
};

export type NewsListResponse = NewsListResponses[keyof NewsListResponses];

export type NotificationsVapidPublicKeyRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/notifications/vapid-public-key/';
};

export type NotificationsVapidPublicKeyRetrieveResponses = {
    200: VapidPublicKey;
};

export type NotificationsVapidPublicKeyRetrieveResponse = NotificationsVapidPublicKeyRetrieveResponses[keyof NotificationsVapidPublicKeyRetrieveResponses];

export type OrdersListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter orders by instrument ticker (e.g., 'AAPL'). If not provided, returns orders for all instruments.
         */
        ticker?: string;
    };
    url: '/api/orders/';
};

export type OrdersListResponses = {
    200: Array<Order>;
};

export type OrdersListResponse = OrdersListResponses[keyof OrdersListResponses];

export type OrdersCancelDestroyData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/orders/cancel/{id}/';
};

export type OrdersCancelDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type OrdersCancelDestroyResponse = OrdersCancelDestroyResponses[keyof OrdersCancelDestroyResponses];

export type OrdersLimitListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter orders by instrument ticker (e.g., 'AAPL'). If not provided, returns orders for all instruments.
         */
        ticker?: string;
    };
    url: '/api/orders/limit/';
};

export type OrdersLimitListResponses = {
    200: Array<LimitOrder>;
};

export type OrdersLimitListResponse = OrdersLimitListResponses[keyof OrdersLimitListResponses];

export type OrdersLimitCreateData = {
    body: CreateLimitOrderRequest;
    path?: never;
    query?: never;
    url: '/api/orders/limit/';
};

export type OrdersLimitCreateErrors = {
    400: OrderCreationError;
};

export type OrdersLimitCreateError = OrdersLimitCreateErrors[keyof OrdersLimitCreateErrors];

export type OrdersLimitCreateResponses = {
    201: LimitOrder;
};

export type OrdersLimitCreateResponse = OrdersLimitCreateResponses[keyof OrdersLimitCreateResponses];

export type OrdersMarketListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter orders by instrument ticker (e.g., 'AAPL'). If not provided, returns orders for all instruments.
         */
        ticker?: string;
    };
    url: '/api/orders/market/';
};

export type OrdersMarketListResponses = {
    200: Array<MarketOrder>;
};

export type OrdersMarketListResponse = OrdersMarketListResponses[keyof OrdersMarketListResponses];

export type OrdersMarketCreateData = {
    body: CreateMarketOrderRequest;
    path?: never;
    query?: never;
    url: '/api/orders/market/';
};

export type OrdersMarketCreateErrors = {
    400: OrderCreationError;
};

export type OrdersMarketCreateError = OrdersMarketCreateErrors[keyof OrdersMarketCreateErrors];

export type OrdersMarketCreateResponses = {
    201: MarketOrder;
};

export type OrdersMarketCreateResponse = OrdersMarketCreateResponses[keyof OrdersMarketCreateResponses];

export type PricesListData = {
    body?: never;
    path?: never;
    query: {
        /**
         * List of ticker symbols to fetch prices for (max 50).
         */
        tickers: Array<string>;
    };
    url: '/api/prices/';
};

export type PricesListResponses = {
    200: Array<PriceDailySummary>;
};

export type PricesListResponse = PricesListResponses[keyof PricesListResponses];

export type PricesRetrieveData = {
    body?: never;
    path: {
        ticker: string;
    };
    query?: never;
    url: '/api/prices/{ticker}/';
};

export type PricesRetrieveResponses = {
    200: PriceDailySummary;
};

export type PricesRetrieveResponse = PricesRetrieveResponses[keyof PricesRetrieveResponses];

export type PricesBarsData = {
    body?: never;
    path?: never;
    query: {
        end_date?: string;
        /**
         * * `SECOND` - SECOND
         * * `MINUTE` - MINUTE
         * * `HOUR` - HOUR
         * * `DAY` - DAY
         * * `WEEK` - WEEK
         * * `MONTH` - MONTH
         * * `QUARTER` - QUARTER
         * * `YEAR` - YEAR
         */
        interval: 'SECOND' | 'MINUTE' | 'HOUR' | 'DAY' | 'WEEK' | 'MONTH' | 'QUARTER' | 'YEAR';
        interval_multiplier?: number;
        start_date: string;
        ticker: string;
    };
    url: '/api/prices/bars/';
};

export type PricesBarsResponses = {
    200: Array<PriceBar>;
};

export type PricesBarsResponse = PricesBarsResponses[keyof PricesBarsResponses];

export type PricesPriceAlertListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
    };
    url: '/api/prices/price-alert/';
};

export type PricesPriceAlertListResponses = {
    200: PaginatedPriceAlertList;
};

export type PricesPriceAlertListResponse = PricesPriceAlertListResponses[keyof PricesPriceAlertListResponses];

export type PricesPriceAlertCreateData = {
    body: PriceAlertCreateRequestWritable;
    path?: never;
    query?: never;
    url: '/api/prices/price-alert/';
};

export type PricesPriceAlertCreateResponses = {
    201: PriceAlertCreate;
};

export type PricesPriceAlertCreateResponse = PricesPriceAlertCreateResponses[keyof PricesPriceAlertCreateResponses];

export type PricesPriceAlertDestroyData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/prices/price-alert/{id}/';
};

export type PricesPriceAlertDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type PricesPriceAlertDestroyResponse = PricesPriceAlertDestroyResponses[keyof PricesPriceAlertDestroyResponses];

export type PricesPriceAlertRetrieveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/prices/price-alert/{id}/';
};

export type PricesPriceAlertRetrieveResponses = {
    200: PriceAlert;
};

export type PricesPriceAlertRetrieveResponse = PricesPriceAlertRetrieveResponses[keyof PricesPriceAlertRetrieveResponses];

export type PricesPriceAlertPartialUpdateData = {
    body?: PatchedPriceAlertRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/prices/price-alert/{id}/';
};

export type PricesPriceAlertPartialUpdateResponses = {
    200: PriceAlert;
};

export type PricesPriceAlertPartialUpdateResponse = PricesPriceAlertPartialUpdateResponses[keyof PricesPriceAlertPartialUpdateResponses];

export type PricesPriceAlertUpdateData = {
    body: PriceAlertRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/prices/price-alert/{id}/';
};

export type PricesPriceAlertUpdateResponses = {
    200: PriceAlert;
};

export type PricesPriceAlertUpdateResponse = PricesPriceAlertUpdateResponses[keyof PricesPriceAlertUpdateResponses];

export type StatisticsAssetAllocationRetrieveData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of top instruments without `Other` position
         */
        instruments_number?: number;
    };
    url: '/api/statistics/asset-allocation/';
};

export type StatisticsAssetAllocationRetrieveResponses = {
    200: AssetAllocation;
};

export type StatisticsAssetAllocationRetrieveResponse = StatisticsAssetAllocationRetrieveResponses[keyof StatisticsAssetAllocationRetrieveResponses];

export type StatisticsCurrentAccountValueRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/statistics/current-account-value/';
};

export type StatisticsCurrentAccountValueRetrieveResponses = {
    200: CurrentAccountValue;
};

export type StatisticsCurrentAccountValueRetrieveResponse = StatisticsCurrentAccountValueRetrieveResponses[keyof StatisticsCurrentAccountValueRetrieveResponses];

export type StatisticsOwnedSharesListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/statistics/owned-shares/';
};

export type StatisticsOwnedSharesListResponses = {
    200: Array<OwnedShare>;
};

export type StatisticsOwnedSharesListResponse = StatisticsOwnedSharesListResponses[keyof StatisticsOwnedSharesListResponses];

export type StatisticsStatisticsMostTradedListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/statistics/statistics/most-traded/';
};

export type StatisticsStatisticsMostTradedListResponses = {
    200: Array<MostTradedItem>;
};

export type StatisticsStatisticsMostTradedListResponse = StatisticsStatisticsMostTradedListResponses[keyof StatisticsStatisticsMostTradedListResponses];

export type StatisticsStatisticsTradingOverviewRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/statistics/statistics/trading-overview/';
};

export type StatisticsStatisticsTradingOverviewRetrieveResponses = {
    200: TradingOverview;
};

export type StatisticsStatisticsTradingOverviewRetrieveResponse = StatisticsStatisticsTradingOverviewRetrieveResponses[keyof StatisticsStatisticsTradingOverviewRetrieveResponses];

export type StatisticsStatsRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/statistics/stats/';
};

export type StatisticsStatsRetrieveResponses = {
    200: InvestorStats;
};

export type StatisticsStatsRetrieveResponse = StatisticsStatsRetrieveResponses[keyof StatisticsStatsRetrieveResponses];

export type StatisticsTransactionsHistoryListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * List of ticker symbols to fetch prices for (max 50).
         */
        tickers?: Array<string>;
        /**
         * Type of positions to fetch: 'open', 'closed', or 'both'
         *
         * * `open` - open
         * * `closed` - closed
         * * `both` - both
         */
        type?: 'open' | 'closed' | 'both';
    };
    url: '/api/statistics/transactions-history/';
};

export type StatisticsTransactionsHistoryListResponses = {
    200: Array<Position>;
};

export type StatisticsTransactionsHistoryListResponse = StatisticsTransactionsHistoryListResponses[keyof StatisticsTransactionsHistoryListResponses];

export type StatusRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/status/';
};

export type StatusRetrieveResponses = {
    /**
     * Application status
     */
    200: StatusResponse;
};

export type StatusRetrieveResponse = StatusRetrieveResponses[keyof StatusRetrieveResponses];

export type TestAdminTestRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/test/admin_test/';
};

export type TestAdminTestRetrieveResponses = {
    /**
     * Admin authentication test successful
     */
    200: AuthTestResponse;
};

export type TestAdminTestRetrieveResponse = TestAdminTestRetrieveResponses[keyof TestAdminTestRetrieveResponses];

export type TestAllTestRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/test/all_test/';
};

export type TestAllTestRetrieveResponses = {
    /**
     * Unauthenticated test successful
     */
    200: SimpleResponse;
};

export type TestAllTestRetrieveResponse = TestAllTestRetrieveResponses[keyof TestAllTestRetrieveResponses];

export type TestAlpacaTestRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/test/alpaca_test/';
};

export type TestAlpacaTestRetrieveResponses = {
    /**
     * Last trade result from Alpaca
     */
    200: SimpleResponse;
};

export type TestAlpacaTestRetrieveResponse = TestAlpacaTestRetrieveResponses[keyof TestAlpacaTestRetrieveResponses];

export type TestPolygonTestRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/test/polygon_test/';
};

export type TestPolygonTestRetrieveResponses = {
    /**
     * Last trade result from Polygon
     */
    200: SimpleResponse;
};

export type TestPolygonTestRetrieveResponse = TestPolygonTestRetrieveResponses[keyof TestPolygonTestRetrieveResponses];

export type TestUsersTestRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/test/users_test/';
};

export type TestUsersTestRetrieveResponses = {
    /**
     * Authentication test successful
     */
    200: AuthTestResponse;
};

export type TestUsersTestRetrieveResponse = TestUsersTestRetrieveResponses[keyof TestUsersTestRetrieveResponses];
